import express from 'express';
import bodyParser from 'body-parser';
import { IntegrationService } from './integrationService.js';
import { Models } from './models.js';
import { requestLogger } from './logger.js';

const app = express();
app.use(bodyParser.json({ verify: rawBodySaver }));
app.use(requestLogger);

app.get('/health', (req, res) => {
  req.log.info('health_check');
  res.json({ status: 'ok', metrics: IntegrationService.getMetrics() });
});

app.post('/integrations/subscribe', (req, res) => {
  const { userId = 'demo-user', planId = 'pro' } = req.body || {};
  const subscription = IntegrationService.createSubscription({ userId, planId });
  req.log.info('subscription_created', { userId, planId });
  res.json(subscription);
});

app.post('/integrations/plaid/link-token', (req, res) => {
  // Token generated by backend; client never sees secrets.
  const token = `plaid-sandbox-${Date.now()}`;
  req.log.info('plaid_link_token_issued', { userId: req.body?.userId });
  res.json({ link_token: token });
});

app.post('/integrations/plaid/exchange', (req, res) => {
  const { publicToken, userId = 'demo-user' } = req.body || {};
  const itemId = `item-${Date.now()}`;
  Models.plaidItems.set(itemId, { id: itemId, userId, publicToken, accessToken: 'server-only' });
  req.log.info('plaid_public_token_exchanged', { userId, itemId });
  res.json({ item_id: itemId });
});

app.post('/webhooks/paypal', (req, res) => {
  try {
    const signature = req.header('x-paypal-signature') || '';
    const rawBody = req.rawBody || JSON.stringify(req.body || {});
    const result = IntegrationService.verifyAndProcessPayPalWebhook(
      rawBody,
      signature,
      req.log,
      req.correlationId,
    );
    res.status(200).json({ status: result.status });
  } catch (err) {
    req.log.error('paypal_webhook_error', { error: err.message });
    res.status(400).json({ error: 'invalid_signature' });
  }
});

app.post('/webhooks/plaid', (req, res) => {
  try {
    const signature = req.header('x-plaid-signature') || '';
    const rawBody = req.rawBody || JSON.stringify(req.body || {});
    const result = IntegrationService.verifyAndProcessPlaidWebhook(
      rawBody,
      signature,
      req.log,
      req.correlationId,
    );
    res.status(200).json({ status: result.status });
  } catch (err) {
    req.log.error('plaid_webhook_error', { error: err.message });
    res.status(400).json({ error: 'invalid_signature' });
  }
});

// PayPal billing endpoints (simulated)
app.post('/billing/paypal/subscription/create', (req, res) => {
  const { userId = 'demo-user', planId = 'plan_pro' } = req.body || {};
  const result = IntegrationService.createPayPalSubscription({ userId, planId });
  req.log.info('paypal_subscription_created', { userId, planId });
  res.json(result);
});

app.post('/billing/paypal/subscription/confirm', (req, res) => {
  const { providerSubscriptionId, userId = 'demo-user' } = req.body || {};
  try {
    const sub = IntegrationService.confirmPayPalSubscription({ providerSubscriptionId, userId });
    const entitlement = IntegrationService.createEntitlement({
      userId,
      productId: sub.planId,
      kind: 'plan',
      durationDays: 30,
    });
    res.json({ subscription: sub, entitlement });
  } catch (e) {
    res.status(400).json({ error: e.message });
  }
});

app.post('/billing/paypal/subscription/cancel', (req, res) => {
  const { providerSubscriptionId } = req.body || {};
  try {
    const sub = IntegrationService.cancelPayPalSubscription({ providerSubscriptionId });
    res.json({ subscription: sub });
  } catch (e) {
    res.status(400).json({ error: e.message });
  }
});

app.post('/outbound/dispatch', async (req, res) => {
  await IntegrationService.dispatchOutboundWebhooks(req.log);
  res.json({ status: 'ok', queueLength: Models.outboundWebhookQueue.length });
});

function rawBodySaver(req, res, buf) {
  req.rawBody = buf.toString();
}

export default app;

// Catalog and entitlement helpers
const catalog = [
  {
    id: 'plan_pro',
    type: 'plan',
    name: 'Pro Plan',
    price: '$14.99/mo',
    description: 'Advanced analytics, instant payouts, and automation.',
  },
  {
    id: 'addon_shift_insights',
    type: 'addon',
    name: 'Shift Insights',
    price: '$4.99/mo',
    description: 'Per-shift profitability and mileage rollups.',
  },
  {
    id: 'onetime_boost',
    type: 'one_time',
    name: 'Boost Pack',
    price: '$19.99',
    description: 'Priority placement for 14 days.',
  },
];

app.get('/catalog', (_req, res) => {
  res.json({ products: catalog });
});

app.get('/entitlements', (req, res) => {
  const userId = req.query.userId || 'demo-user';
  const entitlements = Array.from(Models.entitlements.values()).filter(
    e => e.userId === userId,
  );
  res.json({ entitlements });
});

app.post('/purchase', (req, res) => {
  const { productId, userId = 'demo-user' } = req.body || {};
  const product = catalog.find(p => p.id === productId);
  if (!product) {
    return res.status(400).json({ error: 'unknown_product' });
  }
  const entitlement = IntegrationService.createEntitlement({
    userId,
    productId,
    kind: product.type,
    durationDays: product.type === 'one_time' ? 0 : 30,
  });
  req.log.info('purchase_completed', { userId, productId });
  res.json({ entitlement });
});
